import logging
import asyncio
import uuid
from datetime import datetime
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class SimulationService:
    """
    Handles the mock execution of actions generated by the agents.
    This fulfills the requirement of 'Action Simulation' and 'Logs of action execution'.
    """

    def __init__(self):
        self.simulation_logs: List[Dict[str, Any]] = []

    async def simulate_action(self, action_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main entry point for action simulation.
        Decides which system to mock based on action type.
        """
        action_type = action_data.get("type", "Unknown")
        params = action_data.get("parameters", {})

        simulation_id = str(uuid.uuid4())[:8]
        timestamp = datetime.now().isoformat()

        logger.info(f"Starting simulation [{simulation_id}] for action type: {action_type}")

        result = {
            "simulation_id": simulation_id,
            "timestamp": timestamp,
            "status": "In Progress",
            "execution_logs": [],
            "system_change": {}
        }

        # 1. Simulate Traffic Rerouting (Handoff for rescue-road)
        if action_type == "Reroute":
            result["execution_logs"].append(f"Connecting to rescue-road-engine...")
            await asyncio.sleep(0.5)
            result["execution_logs"].append(f"Pushing route closure for {params.get('affected_road', 'Main St')}")
            result["execution_logs"].append(f"Optimizing alternate path via {params.get('suggested_alternate', 'Side St')}")
            result["system_change"] = {
                "system": "Traffic Control",
                "state_before": "Congested",
                "state_after": "Optimized",
                "metrics": {"avg_speed_increase": "15km/h"}
            }

        # 2. Simulate Emergency Dispatch
        elif action_type == "Dispatch":
            result["execution_logs"].append(f"Alerting Emergency Response Center...")
            await asyncio.sleep(0.8)
            result["execution_logs"].append(f"Mock API Call to Dispatch-911: SUCCESS")
            result["execution_logs"].append(f"Ambulance units assigned to {params.get('location', 'Incident Site')}")
            result["system_change"] = {
                "system": "Emergency Services",
                "state_before": "Idle",
                "state_after": "Active Dispatch",
                "unit_id": f"AMB-{simulation_id}"
            }

        # 3. Simulate Public Alert
        elif action_type == "Alert":
            result["execution_logs"].append(f"Generating broadcast message...")
            await asyncio.sleep(0.3)
            result["execution_logs"].append(f"SMS push initiated for sector: {params.get('location', 'Affected Area')}")
            result["system_change"] = {
                "system": "Notification Hub",
                "broadcast_count": 5240,
                "delivery_rate": "98%"
            }

        result["status"] = "Completed"
        self.simulation_logs.append(result)

        logger.info(f"Simulation [{simulation_id}] completed successfully.")
        return result

    def get_logs(self):
        return self.simulation_logs

simulation_service = SimulationService()
